volumes:
    # тут все в мкл
    # минимальный пипетируемый объем
    min_pipette_volume: 20
    # максимально разрешенный к использованию объем одного пептида
    max_peptide_usage_volume: 480
    # максимально разрешенный объем пула
    max_pool_volume: 4900
labware:
    # тут меняем имена, если захотелось
    # также тут можно поменять позиции, если что-то захочется расставить в другом порядке
    trays:
        - tray_1: 
            name: "Labware16"
            samples: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
        - tray_2:
            name: "Labware17" 
            samples: [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
        - tray_3:
            name: "Labware18" 
            samples: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]
        - tray_4:
            name: "Labware19" 
            samples: [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]
        - tray_5:
            name: "Labware20" 
            samples: [65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]
        - tray_6:
            name: "Labware21" 
            samples: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96]
    delution_plate:
        name: "DelutionDeepWell96"
        # присвоение будет реализовано подряд, т.е. здесь нарисована плашка
        # A01 A02 .. A12
        # B01 B02 .. B12
        # ..
        # H01 H02 .. H12
        samples: [
            1, 9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89,
            2, 10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90,
            3, 11, 19, 27, 35, 43, 51, 59, 67, 75, 83, 91,
            4, 12, 20, 28, 36, 44, 52, 60, 68, 76, 84, 92,
            5, 13, 21, 29, 37, 45, 53, 61, 69, 77, 85, 93,
            6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86, 94,
            7, 15, 23, 31, 39, 47, 55, 63, 71, 79, 87, 95,
            8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96
        ]
    "water":
        name: "MQ"

# прочие параметры, менять в крайнем случае
additional:
    date_preset: "%Y%m%d_%H%M%S"
    delution_factors:
        low: 
            volume: 2
            factor: 0
        medium:
            volume: 10
            factor: 5
        high:
            volume: 20
            factor: 2

            